version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    command: npm start
    environment:
      - PORT=3000
    working_dir: /app
    volumes:
      - .:/app:delegated
      - /app/node_modules
